### ISSUE TITLE
circleci testing is actually failing/not working as expected for container tests

### ISSUE THREAD

**Issue by ckolos** [mozilla/servicebook-web#45]
When running the container build on circleci, there is a test section here:
https://github.com/mozilla/servicebook-web/blob/master/circle.yml#L24-L27

As it turns out, this is actually failing:
```
curl --retry 10 --retry-delay 5 -v 'http://localhost:5000/__version__'

* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 5000 (#0)
> GET /__version__ HTTP/1.1

> User-Agent: curl/7.35.0

> Host: localhost:5000

> Accept: */*

> 

< HTTP/1.1 500 Internal Server Error

< Connection: close
.
.
.

* Closing connection 10
Internal Server ErrorInternal Server ErrorInternal Server ErrorInternal Server ErrorInternal Server ErrorInternal Server ErrorInternal Server ErrorInternal Server ErrorInternal Server ErrorInternal Server ErrorInternal Server Error
```

but I suspect it's passing b/c curl is generating *some* output and that makes circle happy enough.

If I run the container interactively, I get the following message when starting the uwsgi process:
```
<snip>
Traceback (most recent call last):
  File "./wsgiapp-web.py", line 9, in <module>
    application = create_app(ini_file=ini)
  File "/usr/local/lib/python3.5/site-packages/serviceweb/server.py", line 36, in create_app
    oidc = OIDConnect(app, **app.config['oidc'])
KeyError: 'oidc'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
```
I suspect that if these vars are not supplied, which they shouldn't/wouldn't be in circle, the container will not start normally. This should be fixed in some way so that we can do the minimum amount of testing required to know the container is good.

**Comment by tarekziade** [comment]
This was fixed afair
